apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-web

spec:
  replicas: 2

  selector:
    matchLabels:
      app: simple-web

  template:
    metadata:
      labels:
        app: simple-web

    spec:
      containers:
        - name: nginx
          image: ghcr.io/yujajja/simple-web:sha-fc3194967910513f532e4f217d63f9dc0fd400d8
          ports:
            - containerPort: 80