apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-web

spec:
  replicas: 2

  selector:
    matchLabels:
      app: simple-web

  template:
    metadata:
      labels:
        app: simple-web

    spec:
      containers:
        - name: nginx
          image: ghcr.io/yujajja/simple-web:sha-7afdc443bc3b3fd09b40b94c1a3c72a40d910104
          ports:
            - containerPort: 80